Disable pessimistic object deoptimization for calls when the called function doesn't ref this
rollup/rollup pull request #4011
Opened 2021-03-24 16:33 UTC by marijnh

Adds a `referencesThis` flag to `FunctionNode` and uses it to avoid the deoptimization around method calls, as discussed in #3989

Instead of new tests, this reverts some of the test changes made by 3e0aa46d723cac0ac.

Let me know if the `FunctionNode.createScope` kludge is within the limits of kludginess accepted in this project. We could also do a conditional initialization of the property in `initialize`, but that'll lead to different object shapes for no real good reason.

This PR contains:
- [x] bugfix
- [ ] feature
- [ ] refactor
- [ ] documentation
- [ ] other

Are tests included?
- [x] kinda
- [ ] no

Breaking Changes?
- [ ] yes (*breaking changes will not be merged unless absolutely necessary*)
- [x] no

List any relevant issue numbers: #3989

2021-03-24 16:42 UTC, marijnh commented
I'm frankly not terribly interested in writing a bunch of extra tests that make sure that all the `() => true` functions added in src/ast/values.ts do indeed return true, but if the process is so rigid that that's the only way to move this forward, please point me towards what such tests should look like (i.e. how does one produce these special values?)

2021-03-25 06:17 UTC, lukastaegert commented
I would not focus on the values first but rather the loss in coverage for `Identifier.ts`, `LocalVariable.ts` and `MultiExpression.ts`. But I know some of those are tricky to test. I will have a look later.

2021-03-25 08:40 UTC, marijnh commented
For me the details of the code coverage report look like those changes _are_ covered (and they should be, since they will be exercised by just about every method call). I was thinking a refactor of values.ts might be a good idea anyway, to avoid duplication (I had to add identical copies of the new method in eight different places), and that might magically solve the code coverage thing. I'll give that a shot later.

2021-03-25 09:47 UTC, lukastaegert commented
You are right, it is just some sub-cases which are not covered and it might be ok to skip them (though the ones in MultiExpression DO cover relevant situations, at least the "reassigned" and "no init" cases. The one in Identifier is likely impossible to trigger and one could actually use a TypeScript `!` and get rid of it)

A refactoring of `values.ts` is definitely a good thing. Those are mainly used for return values of builtin prototype functions, e.g. `.toString()`.

2021-03-25 09:51 UTC, lukastaegert commented
And thank you for bearing with me a little here. I know the tests are usually a real pain, but it gives us the ability to do large refactorings of the code base with a high level of safety, and this has happened before and will happen again.

2021-03-25 11:04 UTC, marijnh commented
Attached patch does the refactor, but code coverage bot still isn't quite happy. Let me know if you want me to test those `toString` methods or create a weird test that tries to calls a literal.

2021-03-26 05:46 UTC, lukastaegert reviewed
Looks good! I will see if I can add a test for multi-expression. I like what you did with the values. Two very minor suggestions remaining, but in general this looks sound to me.

2021-03-26 05:46 UTC, lukastaegert commented on src/ast/nodes/ThisExpression.ts
> +		for (let parent = this.parent; parent instanceof NodeBase; parent = parent.parent) {
Nice, I like this use of a for loop.

2021-03-26 05:46 UTC, lukastaegert commented on src/ast/nodes/shared/FunctionNode.ts
> +		this.referencesThis = false;
Ah I see. Maybe move it rather into `parseNode`, which is where "initialisation before initialise" usually happens. I.e. `parseNode` is guaranteed to run before child nodes are even created.

2021-03-26 05:46 UTC, lukastaegert commented on src/ast/values.ts
> +	toString() { return '[[UNKNOWN STRING]]' }
Actually these "toString" are only here for debugging and I do not think they turned out to be any useful. We should just remove them all.

2021-03-26 05:55 UTC, lukastaegert requested changes
We should definitely include arrow functions as well! Those do not derive from FunctionNode.

2021-03-26 05:59 UTC, lukastaegert commented
As I am on the code if you do not mind I would push the changes myself. And I would get rid of MultiExpression as I do not know how to trigger it, which is a good sign it may be unnecessary.

2021-03-26 06:15 UTC, lukastaegert approved these changes
If CI passes, this looks good to be merged from my side

2021-03-26 06:22 UTC, lukastaegert commented
Fun fact: Looking at the tests there are a lot of variables that are called removedX. Which are now removed again!

2021-03-26 06:22 UTC, marijnh commented
> We should definitely include arrow functions as well! Those do not derive from FunctionNode.

Good point, thanks for catching that.

2021-03-26 08:27 UTC, marijnh commented
Coverage is unhappy again. How do we proceed here? Should I add a test with some expressions like `1(); (x() ? "hi" : true)();` to get around that? If so, what should I call such a test?

2021-03-26 09:18 UTC, lukastaegert commented
Na, let's leave it.

2021-03-26 09:18 UTC, merged