fix: add missing string prototype methods
rollup/rollup pull request #4299
Opened 2021-12-11 17:06 UTC by dnalborczyk

This PR contains:

- [x] bugfix
- [x] feature
- [ ] refactor
- [ ] documentation
- [ ] other

Are tests included?

- [x] yes (_bugfixes and features will not be merged without tests_)
- [ ] no

Breaking Changes?

- [ ] yes (_breaking changes will not be merged unless absolutely necessary_)
- [x] no

List any relevant issue numbers:

### Description

2021-12-17 05:52 UTC, lukastaegert requested changes
No you are right, `.match` (and `.matchAll`) definitely do NOT return booleans. `.match` returns either an array with extra properties or `null`, and `.matchAll` returns an iterator. We should use `returnsUnknown` for both.
Similarly, `.at` can return `undefined` and should therefore also be a `returnsUnknown`. Checking the other `...at` methods, `.codePointAt` should also be changed to unknown (charAt and charCodeAt seem to return consistent types, though).

Could you adjust those?
Otherwise, I am not sure it makes any sense to mark methods as deprecated, after all, nothing gets every removed from JavaScript so we need to keep supporting it. 😉

2021-12-18 19:30 UTC, dnalborczyk commented
> No you are right, `.match` (and `.matchAll`) definitely do NOT return booleans. `.match` returns either an array with extra properties or `null`, and `.matchAll` returns an iterator. We should use `returnsUnknown` for both. 

ah, ok. I was about to ask. 👍 

> Similarly, `.at` can return `undefined` and should therefore also be a `returnsUnknown`. Checking the other `...at` methods, `.codePointAt` should also be changed to unknown (charAt and charCodeAt seem to return consistent types, though). Could you adjust those? 

I'll fix those as well.

> Otherwise, I am not sure it makes any sense to mark methods as deprecated, after all, nothing gets every removed from JavaScript so we need to keep supporting it. 😉

the comments are more of a reminder. e.g. `trimRight` and `trimLeft` are only mentioned in the MDN as a side note, as being an alias for `trimStart` and `trimEnd`.

2021-12-18 19:44 UTC, dnalborczyk commented
> > Otherwise, I am not sure it makes any sense to mark methods as deprecated, after all, nothing gets every removed from JavaScript so we need to keep supporting it. 😉

> the comments are more of a reminder. e.g. trimRight and trimLeft are only mentioned in the MDN as a side note, as being an alias for trimStart and trimEnd.

in the same vein I'm gonna add those other _deprecated_ "HTML" string methods (blink, link, small, etc.), which are still in V8 (incl. node.js) and possibly other engines.

2021-12-21 06:05 UTC, lukastaegert approved these changes

2021-12-21 06:05 UTC, merged