Bump deps
rollup/rollup pull request #4778
Opened 2022-12-30 15:11 UTC by dnalborczyk

This PR contains:

- [ ] bugfix
- [ ] feature
- [ ] refactor
- [ ] documentation
- [ ] other

Are tests included?

- [ ] yes (_bugfixes and features will not be merged without tests_)
- [ ] no

Breaking Changes?

- [ ] yes (_breaking changes will not be merged unless absolutely necessary_)
- [ ] no

List any relevant issue numbers:

### Description

2022-12-30 17:00 UTC, Hacker011135 reviewed
Ok
![192px](https://user-images.githubusercontent.com/120427499/210094939-8c27b3c2-8f00-4801-bd5f-d401b95d541b.svg)

2022-12-31 05:58 UTC, lukastaegert requested changes
Thanks for the PR. Due to the update, some new unicorn linting rules got pulled in. I think they are reasonable, but you will need to adapt the code to make CI pass.

2022-12-31 12:52 UTC, dnalborczyk commented
> Thanks for the PR. Due to the update, some new unicorn linting rules got pulled in. I think they are reasonable, but you will need to adapt the code to make CI pass.

weird, I could have sworn I ran the liner locally. I'll fix that up.

2023-01-02 06:34 UTC, lukastaegert approved these changes

2023-01-02 06:35 UTC, merged